In [1]:
import numpy as np
import pandas as pd

In [2]:
class_info = pd.read_csv('/home/santosh.sanjeev/model-soups/my_soups/rsna_18/csv/stage_2_detailed_class_info.csv')
class_info

                                  patientId                         class
0      0004cfab-14fd-4e49-80ba-63a80b6bddd6  No Lung Opacity / Not Normal
1      00313ee0-9eaa-42f4-b0ab-c148ed3241cd  No Lung Opacity / Not Normal
2      00322d4d-1c29-4943-afc9-b6754be640eb  No Lung Opacity / Not Normal
3      003d8fa0-6bf1-40ed-b54c-ac657f8495c5                        Normal
4      00436515-870c-4b36-a041-de91049b9ab4                  Lung Opacity
...                                     ...                           ...
30222  c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8                  Lung Opacity
30223  c1edf42b-5958-47ff-a1e7-4f23d99583ba                        Normal
30224  c1f6b555-2eb1-4231-98f6-50a963976431                        Normal
30225  c1f7889a-9ea9-4acb-b64c-b737c929599a                  Lung Opacity
30226  c1f7889a-9ea9-4acb-b64c-b737c929599a                  Lung Opacity

[30227 rows x 2 columns]

In [3]:
# filtered_df = class_info[class_info['class']!= 'No Lung Opacity / Not Normal']
# filtered_df

In [4]:
# count = filtered_df['class'].value_counts()
# count

In [5]:
# filtered_df.to_csv('/home/santosh.sanjeev/model-soups/my_soups/rsna_18/csv/RSNA_wo_not_normal.csv', index=False)

In [6]:
sample_sub = pd.read_csv('/home/santosh.sanjeev/model-soups/my_soups/rsna_18/csv/stage_2_train_labels.csv')
sample_sub

,patientId,x,y,width,height,Target
0,0004cfab-14fd-4e49-80ba-63a80b6bddd6,NaN,NaN,NaN,NaN,0
1,00313ee0-9eaa-42f4-b0ab-c148ed3241cd,NaN,NaN,NaN,NaN,0
2,00322d4d-1c29-4943-afc9-b6754be640eb,NaN,NaN,NaN,NaN,0
3,003d8fa0-6bf1-40ed-b54c-ac657f8495c5,NaN,NaN,NaN,NaN,0
4,00436515-870c-4b36-a041-de91049b9ab4,264.0,152.0,213.0,379.0,1
...,...,...,...,...,...,...
30222,c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8,185.0,298.0,228.0,379.0,1
30223,c1edf42b-5958-47ff-a1e7-4f23d99583ba,NaN,NaN,NaN,NaN,0
30224,c1f6b555-2eb1-4231-98f6-50a963976431,NaN,NaN,NaN,NaN,0
30225,c1f7889a-9ea9-4acb-b64c-b737c929599a,570.0,393.0,261.0,345.0,1
30226,c1f7889a-9ea9-4acb-b64c-b737c929599a,233.0,424.0,201.0,356.0,1

In [7]:
scount = sample_sub['Target'].value_counts()
scount

0    20672
1     9555
Name: Target, dtype: int64

In [8]:
# import os
# folder1_path = 'C:\\Users\\santo\\Downloads\\test\\'
# folder2_path =  'C:\\Users\\santo\\Downloads\\train\\'

# # Get the list of files in folder1 and folder2
# folder1_files = os.listdir(folder1_path)
# folder2_files = os.listdir(folder2_path)

# # Create empty DataFrames to store the results
# test_csv = pd.DataFrame(columns=class_info.columns)
# train_csv = pd.DataFrame(columns=class_info.columns)
# remaining_csv = pd.DataFrame(columns=class_info.columns)

# # Iterate through folder1
# test_count = 0

# for file_name in folder1_files:
# #     print(file_name[:-4])
#     if file_name[:-4] in class_info['patientId'].values:
#         # If the file name matches, append the corresponding row to test_csv
#         test_csv = test_csv.append(class_info[class_info['patientId'] == file_name[:-4]])
#     test_count+=1
# train_count = 0
# # Iterate through folder2
# for file_name in folder2_files:
#     if file_name[:-4] in class_info['patientId'].values:
#         # If the file name matches, append the corresponding row to train_csv
#         train_csv = train_csv.append(class_info[class_info['patientId'] == file_name[:-4]])
#     train_count+=1

In [9]:
df_temp = class_info.drop_duplicates(subset=['patientId'])
df_temp

                                  patientId                         class
0      0004cfab-14fd-4e49-80ba-63a80b6bddd6  No Lung Opacity / Not Normal
1      00313ee0-9eaa-42f4-b0ab-c148ed3241cd  No Lung Opacity / Not Normal
2      00322d4d-1c29-4943-afc9-b6754be640eb  No Lung Opacity / Not Normal
3      003d8fa0-6bf1-40ed-b54c-ac657f8495c5                        Normal
4      00436515-870c-4b36-a041-de91049b9ab4                  Lung Opacity
...                                     ...                           ...
30219  c1e73a4e-7afe-4ec5-8af6-ce8315d7a2f2                  Lung Opacity
30221  c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8                  Lung Opacity
30223  c1edf42b-5958-47ff-a1e7-4f23d99583ba                        Normal
30224  c1f6b555-2eb1-4231-98f6-50a963976431                        Normal
30225  c1f7889a-9ea9-4acb-b64c-b737c929599a                  Lung Opacity

[26684 rows x 2 columns]

In [10]:
count = df_temp['class'].value_counts()
count

No Lung Opacity / Not Normal    11821
Normal                           8851
Lung Opacity                     6012
Name: class, dtype: int64

In [11]:
df_temp1 = sample_sub.drop_duplicates(subset=['patientId'])
df_temp1

,patientId,x,y,width,height,Target
0,0004cfab-14fd-4e49-80ba-63a80b6bddd6,NaN,NaN,NaN,NaN,0
1,00313ee0-9eaa-42f4-b0ab-c148ed3241cd,NaN,NaN,NaN,NaN,0
2,00322d4d-1c29-4943-afc9-b6754be640eb,NaN,NaN,NaN,NaN,0
3,003d8fa0-6bf1-40ed-b54c-ac657f8495c5,NaN,NaN,NaN,NaN,0
4,00436515-870c-4b36-a041-de91049b9ab4,264.0,152.0,213.0,379.0,1
...,...,...,...,...,...,...
30219,c1e73a4e-7afe-4ec5-8af6-ce8315d7a2f2,666.0,418.0,186.0,223.0,1
30221,c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8,609.0,464.0,240.0,284.0,1
30223,c1edf42b-5958-47ff-a1e7-4f23d99583ba,NaN,NaN,NaN,NaN,0
30224,c1f6b555-2eb1-4231-98f6-50a963976431,NaN,NaN,NaN,NaN,0
30225,c1f7889a-9ea9-4acb-b64c-b737c929599a,570.0,393.0,261.0,345.0,1

In [12]:
count = df_temp1['Target'].value_counts()
count

0    20672
1     6012
Name: Target, dtype: int64

In [13]:
# import random
# random.seed(42)  # for reproducibility
# df_temp1['random_number'] = [random.random() for _ in range(len(df_temp1))]

# # Step 2: Assign 'train', 'val', or 'test' based on probabilities
# df_temp1['split'] = pd.cut(df_temp1['random_number'], bins=[0, 0.8, 0.9, 1], labels=['train', 'val', 'test'])
# df_temp1.drop(columns=['random_number'], inplace=True)

# # Step 3: Calculate counts
# counts = df_temp1.groupby(['split', 'Target']).size().unstack(fill_value=0)
# total_counts = counts.sum(axis=1)

# print("Counts by split and target:")
# print(counts)

# print("\nTotal counts by split:")
# print(total_counts)

In [14]:
# df_temp1

In [15]:
# merged_df.to_csv('RSNA_final_df_with_class_info.csv', index=False)

In [16]:
merged_df = pd.merge(df_temp, df_temp1, on='patientId', how='inner')
merged_df

,patientId,class,x,y,width,height,Target
0,0004cfab-14fd-4e49-80ba-63a80b6bddd6,No Lung Opacity / Not Normal,NaN,NaN,NaN,NaN,0
1,00313ee0-9eaa-42f4-b0ab-c148ed3241cd,No Lung Opacity / Not Normal,NaN,NaN,NaN,NaN,0
2,00322d4d-1c29-4943-afc9-b6754be640eb,No Lung Opacity / Not Normal,NaN,NaN,NaN,NaN,0
3,003d8fa0-6bf1-40ed-b54c-ac657f8495c5,Normal,NaN,NaN,NaN,NaN,0
4,00436515-870c-4b36-a041-de91049b9ab4,Lung Opacity,264.0,152.0,213.0,379.0,1
...,...,...,...,...,...,...,...
26679,c1e73a4e-7afe-4ec5-8af6-ce8315d7a2f2,Lung Opacity,666.0,418.0,186.0,223.0,1
26680,c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8,Lung Opacity,609.0,464.0,240.0,284.0,1
26681,c1edf42b-5958-47ff-a1e7-4f23d99583ba,Normal,NaN,NaN,NaN,NaN,0
26682,c1f6b555-2eb1-4231-98f6-50a963976431,Normal,NaN,NaN,NaN,NaN,0
26683,c1f7889a-9ea9-4acb-b64c-b737c929599a,Lung Opacity,570.0,393.0,261.0,345.0,1

In [17]:
merged_df_v1 = merged_df[merged_df['class']!= 'No Lung Opacity / Not Normal']
merged_df_v1

,patientId,class,x,y,width,height,Target
3,003d8fa0-6bf1-40ed-b54c-ac657f8495c5,Normal,NaN,NaN,NaN,NaN,0
4,00436515-870c-4b36-a041-de91049b9ab4,Lung Opacity,264.0,152.0,213.0,379.0,1
7,00704310-78a8-4b38-8475-49f4573b2dbb,Lung Opacity,323.0,577.0,160.0,104.0,1
9,009482dc-3db5-48d4-8580-5c89c4f01334,Normal,NaN,NaN,NaN,NaN,0
10,009eb222-eabc-4150-8121-d5a6d06b8ebf,Normal,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...
26679,c1e73a4e-7afe-4ec5-8af6-ce8315d7a2f2,Lung Opacity,666.0,418.0,186.0,223.0,1
26680,c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8,Lung Opacity,609.0,464.0,240.0,284.0,1
26681,c1edf42b-5958-47ff-a1e7-4f23d99583ba,Normal,NaN,NaN,NaN,NaN,0
26682,c1f6b555-2eb1-4231-98f6-50a963976431,Normal,NaN,NaN,NaN,NaN,0
26683,c1f7889a-9ea9-4acb-b64c-b737c929599a,Lung Opacity,570.0,393.0,261.0,345.0,1

In [37]:
# df = pd.read_csv('/home/santosh.sanjeev/model-soups/my_soups/rsna_18/csv/stage_2_train_labels.csv')

# # Find duplicate patientIDs
# duplicate_patientIDs = df[df.duplicated(subset=['patientId'], keep=False)]

# # Create a new DataFrame with rows containing duplicate patientIDs
# duplicates_df = df[df['patientId'].isin(duplicate_patientIDs['patientId'])]

# # Remove the duplicates from the original DataFrame
# df = df[~df['patientId'].isin(duplicate_patientIDs['patientId'])]

In [38]:
# duplicates_df

In [29]:
# import random
# random.seed(42)  # for reproducibility
# merged_df['random_number'] = [random.random() for _ in range(len(merged_df))]

# # Step 2: Assign 'train', 'val', or 'test' based on probabilities
# merged_df['split'] = pd.cut(merged_df['random_number'], bins=[0, 0.8, 0.9, 1], labels=['train', 'val', 'test'])
# merged_df.drop(columns=['random_number'], inplace=True)

# # Step 3: Calculate counts
# counts = merged_df.groupby(['split', 'Target']).size().unstack(fill_value=0)
# total_counts = counts.sum(axis=1)

# print("Counts by split and target:")
# print(counts)

# print("\nTotal counts by split:")
# print(total_counts)

Counts by split and target:
Target      0     1
split
train   16567  4807
val      2038   623
test     2067   582

Total counts by split:
split
train    21374
val       2661
test      2649
dtype: int64

In [18]:
# merged_df

In [34]:
# merged_df.to_csv('RSNA_final_df_with_class_info.csv', index=False)

In [19]:
# df_filtered = merged_df[merged_df['class'] != 'No Lung Opacity / Not Normal']
# df_filtered

In [21]:
import random
random.seed(42)  # for reproducibility
merged_df_v1['random_number'] = [random.random() for _ in range(len(merged_df_v1))]

# Step 2: Assign 'train', 'val', or 'test' based on probabilities
merged_df_v1['split'] = pd.cut(merged_df_v1['random_number'], bins=[0, 0.8, 0.9, 1], labels=['train', 'val', 'test'])
merged_df_v1.drop(columns=['random_number'], inplace=True)

# Step 3: Calculate counts
counts = merged_df_v1.groupby(['split', 'class']).size().unstack(fill_value=0)
total_counts = counts.sum(axis=1)

print("Counts by split and target:")
print(counts)

print("\nTotal counts by split:")
print(total_counts)

Counts by split and target:
class  Lung Opacity  Normal
split
train          4822    7089
val             609     860
test            581     902

Total counts by split:
split
train    11911
val       1469
test      1483
dtype: int64

/tmp/ipykernel_698717/404447517.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df_v1['random_number'] = [random.random() for _ in range(len(merged_df_v1))]
/tmp/ipykernel_698717/404447517.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df_v1['split'] = pd.cut(merged_df_v1['random_number'], bins=[0, 0.8, 0.9, 1], labels=['train', 'val', 'test'])
/tmp/ipykernel_698717/404447517.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df_v1.drop(columns=['random_number'], inplace=True)

In [22]:
merged_df_v1

,patientId,class,x,y,width,height,Target,split
3,003d8fa0-6bf1-40ed-b54c-ac657f8495c5,Normal,NaN,NaN,NaN,NaN,0,train
4,00436515-870c-4b36-a041-de91049b9ab4,Lung Opacity,264.0,152.0,213.0,379.0,1,train
7,00704310-78a8-4b38-8475-49f4573b2dbb,Lung Opacity,323.0,577.0,160.0,104.0,1,train
9,009482dc-3db5-48d4-8580-5c89c4f01334,Normal,NaN,NaN,NaN,NaN,0,train
10,009eb222-eabc-4150-8121-d5a6d06b8ebf,Normal,NaN,NaN,NaN,NaN,0,train
...,...,...,...,...,...,...,...,...
26679,c1e73a4e-7afe-4ec5-8af6-ce8315d7a2f2,Lung Opacity,666.0,418.0,186.0,223.0,1,train
26680,c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8,Lung Opacity,609.0,464.0,240.0,284.0,1,test
26681,c1edf42b-5958-47ff-a1e7-4f23d99583ba,Normal,NaN,NaN,NaN,NaN,0,train
26682,c1f6b555-2eb1-4231-98f6-50a963976431,Normal,NaN,NaN,NaN,NaN,0,val
26683,c1f7889a-9ea9-4acb-b64c-b737c929599a,Lung Opacity,570.0,393.0,261.0,345.0,1,train

In [23]:
merged_df_v1.to_csv('/home/santosh.sanjeev/model-soups/my_soups/rsna_18/csv/final_dataset_wo_not_normal_cases.csv')